export type DiscountVariant = {
  id?: number;
  product_id?: number | null;
  sku?: string | null;
  price?: number | string | null;
  stock?: number | string | null;
  label?: string | null;
  product?: { id: number; name: string } | null;
};

export type DiscountVariantItem = {
  __key?: string;
  id?: number;
  discountId?: number;
  productId?: number | null;
  productVariantId?: number;
  isActive?: boolean;
  valueType?: string | number;
  value?: number | string | null;
  maxDiscount?: number | string | null;
  promoStock?: number | string | null;
  purchaseLimit?: number | string | null;
  variant?: DiscountVariant | null;
  product_variant_id?: number;
  product_id?: number;
  is_active?: number;
  value_type?: any;
  max_discount?: any;
  promo_stock?: any;
  purchase_limit?: any;
};

export type DiscountRecord = {
  __key?: string;
  id?: number | string | null;
  name?: string | null;
  code?: string | null;
  description?: string | null;
  valueType?: number;
  value?: string | number | null;
  maxDiscount?: string | number | null;
  appliesTo?: number;
  minOrderAmount?: string | number | null;
  isActive?: number;
  startedAt?: string | null;
  expiredAt?: string | null;
  isEcommerce?: number;
  isPos?: number;
  qty?: number | null;
  variantItems?: DiscountVariantItem[];
  value_type?: number;
  max_discount?: string | number | null;
  applies_to?: number;
  min_order_amount?: string | number | null;
  is_active?: number;
  started_at?: string | null;
  expired_at?: string | null;
  is_ecommerce?: number;
  is_pos?: number;
};
